"""Allow nullable for event fields

Revision ID: 41face7cb9ba
Revises: 135e26710749
Create Date: 2025-08-02 17:03:53.725911

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '41face7cb9ba'
down_revision = '135e26710749'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=180),
               nullable=True)
        batch_op.alter_column('capacity',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=postgresql.ENUM('DRAFT', 'PUBLISHED', 'CANCELLED', name='eventstatus'),
               nullable=True)
        batch_op.alter_column('start_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('end_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('created_by_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.alter_column('created_by_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('end_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('start_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=postgresql.ENUM('DRAFT', 'PUBLISHED', 'CANCELLED', name='eventstatus'),
               nullable=False)
        batch_op.alter_column('capacity',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=180),
               nullable=False)

    # ### end Alembic commands ###
